### ISSUE TITLE
fix: stub is broken for cjs

### ISSUE THREAD

**Issue by antfu** [unjs/siroc#219]
**🐛 The bug**
What isn't working? Describe what the bug is.

`siroc dev`

Both `index.js`, `index.mjs`, `index.d.ts` are 

```ts
export * from './../src/index'
```

without wrapping with `jiti`

**Comment by danielroe** [comment]
@antfu What would you expect the files to contain? And what isn't working?

**Comment by antfu** [comment]
Shouldn't `.js` contain a wrapper with `jiti` and `module.exports`?
